name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm ci

      - name: Run build task
        run: npm run build

      - name: Debug
        run: whoami & pwd

      - name: Copy to server dir
        run: cp -R dist/* ${{ secrets.REMOTE_TARGET }}
